# Generated by Django 6.0.6 on 2026-09-08 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(choices=[('Interior Design', 'Interior Design'), ('Living Room', 'Living Room'), ('Bedroom', 'Bedroom'), ('Kitchen', 'Kitchen'), ('Office', 'Office'), ('Architecture', 'Architecture'), ('Tips & Ideas', 'Tips & Ideas')], max_length=50)),
                ('featured_image', models.ImageField(upload_to='blog/')),
                ('excerpt', models.TextField(blank=True, max_length=300)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
